package model

import (
	"math/rand"
)

func SeedData() []EmailAccount {
	emails1 := []Email{
		{
			Id:          rand.Intn(100),
			Path:        "/1/email1",
			From:        "john@example.com",
			To:          "jane@example.com",
			DeliveredTo: "jane@example.com",
			Subject:     "Meeting Tomorrow",
			Text:        "Hi Jane, I just wanted to remind you about our meeting tomorrow at 2pm.",
			HTML:        "",
			Date:        "2022-03-02T10:00:00Z",
			IsSeen:      false,
			IsImportant: true,
			IsAnswered:  false,
			IsSelected:  false,
		},
		{
			Id:          rand.Intn(100),
			Path:        "/1/email2",
			From:        "jane@example.com",
			To:          "john@example.com",
			DeliveredTo: "john@example.com",
			Subject:     "RE: Meeting Tomorrow",
			Text:        "Thanks for the reminder, John. I'll be there at 2pm tomorrow.",
			HTML:        "",
			Date:        "2022-03-02T11:00:00Z",
			IsSeen:      false,
			IsImportant: false,
			IsAnswered:  true,
			IsSelected:  false,
		},
		{
			Id:          rand.Intn(100),
			Path:        "/1/email3",
			From:        "bob@example.com",
			To:          "john@example.com",
			DeliveredTo: "john@example.com",
			Subject:     "Project Update",
			Text:        "Hi John, just wanted to give you a quick update on the project. We're making good progress and should be able to hit our deadline.",
			HTML:        "",
			Date:        "2022-03-01T15:30:00Z",
			IsSeen:      true,
			IsImportant: false,
			IsAnswered:  false,
			IsSelected:  false,
		},
		{
			Id:          rand.Intn(100),
			Path:        "/1/email4",
			From:        "alice@example.com",
			To:          "john@example.com",
			DeliveredTo: "john@example.com",
			Subject:     "Important Announcement",
			Text:        "Hello, we have an important company-wide announcement. Please see the attached document for details.",
			HTML:        "",
			Date:        "2022-02-28T09:15:00Z",
			IsSeen:      true,
			IsImportant: true,
			IsAnswered:  false,
			IsSelected:  false,
		},
		{
			Id:          rand.Intn(100),
			Path:        "/1/email5",
			From:        "sales@example.com",
			To:          "john@example.com",
			DeliveredTo: "john@example.com",
			Subject:     "Special Offer",
			Text:        "Don't miss out on our special offer! Use code SPECIAL10 for 10% off your next purchase.",
			HTML:        "",
			Date:        "2022-02-25T14:00:00Z",
			IsSeen:      true,
			IsImportant: false,
			IsAnswered:  false,
			IsSelected:  false,
		},
	}
	emails2 := []Email{
		{
			Id:          rand.Intn(100),
			Path:        "/2/email1",
			From:        "john@example.com",
			To:          "jane@example.com",
			DeliveredTo: "jane@example.com",
			Subject:     "Meeting Tomorrow",
			Text:        "Hi Jane, I just wanted to remind you about our meeting tomorrow at 2pm.",
			HTML:        "",
			Date:        "2022-03-02T10:00:00Z",
			IsSeen:      false,
			IsImportant: true,
			IsAnswered:  false,
			IsSelected:  false,
		},
		{
			Id:          rand.Intn(100),
			Path:        "/2/email2",
			From:        "jane@example.com",
			To:          "john@example.com",
			DeliveredTo: "john@example.com",
			Subject:     "RE: Meeting Tomorrow",
			Text:        "Thanks for the reminder, John. I'll be there at 2pm tomorrow.",
			HTML:        "",
			Date:        "2022-03-02T11:00:00Z",
			IsSeen:      false,
			IsImportant: false,
			IsAnswered:  true,
			IsSelected:  false,
		},
		{
			Id:          rand.Intn(100),
			Path:        "/2/email3",
			From:        "bob@example.com",
			To:          "john@example.com",
			DeliveredTo: "john@example.com",
			Subject:     "Project Update",
			Text:        "Hi John, just wanted to give you a quick update on the project. We're making good progress and should be able to hit our deadline.",
			HTML:        "",
			Date:        "2022-03-01T15:30:00Z",
			IsSeen:      true,
			IsImportant: false,
			IsAnswered:  false,
			IsSelected:  false,
		},
		{
			Id:          rand.Intn(100),
			Path:        "/2/email4",
			From:        "alice@example.com",
			To:          "john@example.com",
			DeliveredTo: "john@example.com",
			Subject:     "Important Announcement",
			Text:        "Hello, we have an important company-wide announcement. Please see the attached document for details.",
			HTML:        "",
			Date:        "2022-02-28T09:15:00Z",
			IsSeen:      true,
			IsImportant: true,
			IsAnswered:  false,
			IsSelected:  false,
		},
		{
			Id:          rand.Intn(100),
			Path:        "/2/email5",
			From:        "sales@example.com",
			To:          "john@example.com",
			DeliveredTo: "john@example.com",
			Subject:     "Special Offer",
			Text:        "Don't miss out on our special offer! Use code SPECIAL10 for 10% off your next purchase.",
			HTML:        "",
			Date:        "2022-02-25T14:00:00Z",
			IsSeen:      true,
			IsImportant: false,
			IsAnswered:  false,
			IsSelected:  false,
		},
	}
	emails3 := []Email{
		{
			Id:          rand.Intn(100),
			Path:        "/3/email1",
			From:        "john@example.com",
			To:          "jane@example.com",
			DeliveredTo: "jane@example.com",
			Subject:     "Meeting Tomorrow",
			Text:        "Hi Jane, I just wanted to remind you about our meeting tomorrow at 2pm.",
			HTML:        "",
			Date:        "2022-03-02T10:00:00Z",
			IsSeen:      false,
			IsImportant: true,
			IsAnswered:  false,
			IsSelected:  false,
		},
		{
			Id:          rand.Intn(100),
			Path:        "/3/email2",
			From:        "jane@example.com",
			To:          "john@example.com",
			DeliveredTo: "john@example.com",
			Subject:     "RE: Meeting Tomorrow",
			Text:        "Thanks for the reminder, John. I'll be there at 2pm tomorrow.",
			HTML:        "",
			Date:        "2022-03-02T11:00:00Z",
			IsSeen:      false,
			IsImportant: false,
			IsAnswered:  true,
			IsSelected:  false,
		},
		{
			Id:          rand.Intn(100),
			Path:        "/3/email3",
			From:        "bob@example.com",
			To:          "john@example.com",
			DeliveredTo: "john@example.com",
			Subject:     "Project Update",
			Text:        "Hi John, just wanted to give you a quick update on the project. We're making good progress and should be able to hit our deadline.",
			HTML:        "",
			Date:        "2022-03-01T15:30:00Z",
			IsSeen:      true,
			IsImportant: false,
			IsAnswered:  false,
			IsSelected:  false,
		},
		{
			Id:          rand.Intn(100),
			Path:        "/3/email4",
			From:        "alice@example.com",
			To:          "john@example.com",
			DeliveredTo: "john@example.com",
			Subject:     "Important Announcement",
			Text:        "Hello, we have an important company-wide announcement. Please see the attached document for details.",
			HTML:        "",
			Date:        "2022-02-28T09:15:00Z",
			IsSeen:      true,
			IsImportant: true,
			IsAnswered:  false,
			IsSelected:  false,
		},
		{
			Id:          rand.Intn(100),
			Path:        "/3/email5",
			From:        "sales@example.com",
			To:          "john@example.com",
			DeliveredTo: "john@example.com",
			Subject:     "Special Offer",
			Text:        "Don't miss out on our special offer! Use code SPECIAL10 for 10% off your next purchase.",
			HTML:        "",
			Date:        "2022-02-25T14:00:00Z",
			IsSeen:      true,
			IsImportant: false,
			IsAnswered:  false,
			IsSelected:  false,
		},
	}
	emails4 := []Email{
		{
			Id:          rand.Intn(100),
			Path:        "/4/email1",
			From:        "john@example.com",
			To:          "jane@example.com",
			DeliveredTo: "jane@example.com",
			Subject:     "Meeting Tomorrow",
			Text:        "Hi Jane, I just wanted to remind you about our meeting tomorrow at 2pm.",
			HTML:        "",
			Date:        "2022-03-02T10:00:00Z",
			IsSeen:      false,
			IsImportant: true,
			IsAnswered:  false,
			IsSelected:  false,
		},
		{
			Id:          rand.Intn(100),
			Path:        "/4/email2",
			From:        "jane@example.com",
			To:          "john@example.com",
			DeliveredTo: "john@example.com",
			Subject:     "RE: Meeting Tomorrow",
			Text:        "Thanks for the reminder, John. I'll be there at 2pm tomorrow.",
			HTML:        "",
			Date:        "2022-03-02T11:00:00Z",
			IsSeen:      false,
			IsImportant: false,
			IsAnswered:  true,
			IsSelected:  false,
		},
		{
			Id:          rand.Intn(100),
			Path:        "/4/email3",
			From:        "bob@example.com",
			To:          "john@example.com",
			DeliveredTo: "john@example.com",
			Subject:     "Project Update",
			Text:        "Hi John, just wanted to give you a quick update on the project. We're making good progress and should be able to hit our deadline.",
			HTML:        "",
			Date:        "2022-03-01T15:30:00Z",
			IsSeen:      true,
			IsImportant: false,
			IsAnswered:  false,
			IsSelected:  false,
		},
		{
			Id:          rand.Intn(100),
			Path:        "/4/email4",
			From:        "alice@example.com",
			To:          "john@example.com",
			DeliveredTo: "john@example.com",
			Subject:     "Important Announcement",
			Text:        "Hello, we have an important company-wide announcement. Please see the attached document for details.",
			HTML:        "",
			Date:        "2022-02-28T09:15:00Z",
			IsSeen:      true,
			IsImportant: true,
			IsAnswered:  false,
			IsSelected:  false,
		},
		{
			Id:          rand.Intn(100),
			Path:        "/4/email5",
			From:        "sales@example.com",
			To:          "john@example.com",
			DeliveredTo: "john@example.com",
			Subject:     "Special Offer",
			Text:        "Don't miss out on our special offer! Use code SPECIAL10 for 10% off your next purchase.",
			HTML:        "",
			Date:        "2022-02-25T14:00:00Z",
			IsSeen:      true,
			IsImportant: false,
			IsAnswered:  false,
			IsSelected:  false,
		},
	}
	emails5 := []Email{
		{
			Id:          rand.Intn(100),
			Path:        "/5/email1",
			From:        "john@example.com",
			To:          "jane@example.com",
			DeliveredTo: "jane@example.com",
			Subject:     "Meeting Tomorrow",
			Text:        "Hi Jane, I just wanted to remind you about our meeting tomorrow at 2pm.",
			HTML:        "",
			Date:        "2022-03-02T10:00:00Z",
			IsSeen:      false,
			IsImportant: true,
			IsAnswered:  false,
			IsSelected:  false,
		},
		{
			Id:          rand.Intn(100),
			Path:        "/5/email2",
			From:        "jane@example.com",
			To:          "john@example.com",
			DeliveredTo: "john@example.com",
			Subject:     "RE: Meeting Tomorrow",
			Text:        "Thanks for the reminder, John. I'll be there at 2pm tomorrow.",
			HTML:        "",
			Date:        "2022-03-02T11:00:00Z",
			IsSeen:      false,
			IsImportant: false,
			IsAnswered:  true,
			IsSelected:  false,
		},
		{
			Id:          rand.Intn(100),
			Path:        "/5/email3",
			From:        "bob@example.com",
			To:          "john@example.com",
			DeliveredTo: "john@example.com",
			Subject:     "Project Update",
			Text:        "Hi John, just wanted to give you a quick update on the project. We're making good progress and should be able to hit our deadline.",
			HTML:        "",
			Date:        "2022-03-01T15:30:00Z",
			IsSeen:      true,
			IsImportant: false,
			IsAnswered:  false,
			IsSelected:  false,
		},
		{
			Id:          rand.Intn(100),
			Path:        "/5/email4",
			From:        "alice@example.com",
			To:          "john@example.com",
			DeliveredTo: "john@example.com",
			Subject:     "Important Announcement",
			Text:        "Hello, we have an important company-wide announcement. Please see the attached document for details.",
			HTML:        "",
			Date:        "2022-02-28T09:15:00Z",
			IsSeen:      true,
			IsImportant: true,
			IsAnswered:  false,
			IsSelected:  false,
		},
		{
			Id:          rand.Intn(100),
			Path:        "/5/email5",
			From:        "sales@example.com",
			To:          "john@example.com",
			DeliveredTo: "john@example.com",
			Subject:     "Special Offer",
			Text:        "Don't miss out on our special offer! Use code SPECIAL10 for 10% off your next purchase.",
			HTML:        "",
			Date:        "2022-02-25T14:00:00Z",
			IsSeen:      true,
			IsImportant: false,
			IsAnswered:  false,
			IsSelected:  false,
		},
	}
	emailAccounts := []EmailAccount{
		{
			AccountType:       "regular",
			ShortName:         "Inbox",
			Email:             "john.smith@example.com",
			InboxShellCommand: "ls /path/to/inbox",
			TrashFolder:       "/path/to/trash",
			DeliveryTransport: "smtp",
			Emails:            emails1,
		},
		{
			AccountType:       "virtual",
			ShortName:         "Important",
			Email:             "jane.doe@example.com",
			InboxShellCommand: "notmuch search --output=files tag:inbox",
			TrashFolder:       "/path/to/trash",
			DeliveryTransport: "smtp",
			Emails:            emails2,
		},
		{
			AccountType:       "regular",
			ShortName:         "Work",
			Email:             "bob.johnson@example.com",
			InboxShellCommand: "ls /path/to/inbox",
			TrashFolder:       "/path/to/trash",
			DeliveryTransport: "smtp",
			Emails:            emails3,
		},
		{
			AccountType:       "virtual",
			ShortName:         "Home",
			Email:             "alice.williams@example.com",
			InboxShellCommand: "notmuch search --output=files tag:inbox",
			TrashFolder:       "/path/to/trash",
			DeliveryTransport: "smtp",
			Emails:            emails4,
		},
		{
			AccountType:       "regular",
			ShortName:         "Football",
			Email:             "charlie.brown@example.com",
			InboxShellCommand: "ls /path/to/inbox",
			TrashFolder:       "/path/to/trash",
			DeliveryTransport: "smtp",
			Emails:            emails5,
		},
	}
	return emailAccounts
}
